peopledoc/django-formidable

demo/tests/test_forms.py, formidable/forms/field_builder.py
When a field is not disabled, the attribute `disabled` does not appear
in the input html balise. Whatever the value is, if the disabled
attribute appears, the field is automatically disabled.
=> Does not set the disabled attribute in widget

demo/tests/test_end_point.py, demo/tests/test_forms.py, demo/tests/test_from_form.py, formidable/forms/fields.py, formidable/forms/widgets.py
Email Field was already handle by serializer on creation, edition and contextualized rendering. 
Only the case in python builder was missing, the PR added it and few tests about above case.
=> Add email field

README.rst, demo/demo/settings.py, demo/tests/test_permissions.py, docs/source/install.rst, formidable/permissions.py, formidable/views.py
Added a hook in order to plug custom permissions on each view provided by Formidable.
The permissions classes can be added through settings with a pyramidal policy
- If no settings key is provided, the NoOne permission is apply
- If the global FORMIDABLE_DEFAULT_PERMISSION is provided, these classes are applied
- If the specific key (depending the view) is specified, the permissions classes are applied.
=> Custom permissions

formidable/views.py
In ValdiationView, the method to get the formidable object was "static".
Just check the "pk" key in the kwargs dict of the view. But, if the
client need another method to fetche the formidable object, no way was
offer. The main idea is to provide a method overridable in order to have
customisable point for the client.
=> Add a method in order to get the formidable object

demo/tests/test_forms.py, formidable/models.py, setup.py
I added a proxy static method to create an instance of `Formidable` more easily from a JSON definition:
```python
>>> form = Formidable.from_json(schema_definition)
```
This implements an alternative constructor, using `FormidableSerializer`.
I also added some tests against valid/invalid JSON schema.
_This is just a suggestion @moumoutte · Feel free to reject the PR!_ :wink:
=> [models] Add static method to create an instance from JSON

CHANGELOG.rst, docs/Makefile, docs/source/conf.py, tox.ini
closes #131
```
$ rm docs/build/ -Rf && tox -re docs
GLOB sdist-make: /home/novapost/Projets/PeopleAsk/django-formidable/setup.py
[SNIP... SNIP... SNIP...]
/home/novapost/Projets/PeopleAsk/django-formidable/docs/source/forms.rst:14: WARNING: autodoc: failed to import class u'Formidable' from module u'formidable.models'; the following exception was raised:
Traceback (most recent call last):
[SNIP... SNIP... SNIP...]
AppRegistryNotReady: Apps aren't loaded yet.
/home/novapost/Projets/PeopleAsk/django-formidable/docs/source/forms.rst:275: WARNING: autodoc: failed to import module u'formidable.forms.fields'; the following exception was raised:
[SNIP... SNIP... SNIP...]
build succeeded, 3 warnings.
Build finished. The HTML pages are in build/html.
summary
docs: commands succeeded …
```
=> Fix warnings caused by autodoc when building Sphinx documentation

CHANGELOG.rst, circle.yml
It looks like the ``.egg`` file generated when build "N" is happening is not always wiped out at the end of this build. As a consequence, the build "N+1" can't start because there's a "zip error" similar to [this trac issue](https://trac.edgewall.org/ticket/7014).
As a matter of fact, the global ``python setup.py install`` is useless, since `tox` will install the package in each isolated virtualenv. So the solution to this issue was to *override* the dependency setup by installing the most recent version of tox and avoid the misbehaving command
=> Fix setup.py install bug

CHANGELOG.rst, Makefile, circle.yml, tox.ini
Use-case: Developer "X" is working on a feature, and is adding a "isort" regression somewhere.
Issue: "X" is pushing the new branch and it fails because **CircleCI** launches two commands: tox & the isort check.
Solution: since isort is a Python dependency and that tox knows how to install python packages in an isolated environment, tox is able to perform this extra check without having to run two commands. *"One command to rule them all"*.
ToDo:
=> moving isort tests to the tox file

CHANGELOG.rst, demo/demo/builder/static/assets/csrftoken.js, demo/demo/builder/templates/formidable/formidable_base.html, demo/demo/builder/urls.py, demo/demo/settings.py, docs/source/install.rst
* Once your virtualenv is installed (using only Django<1.9 at the moment), you can log on the website using the ``/admin`` URL.
* access the ``forms/`` URL and try to edit a form,
* if you try to save, it works.
Try with removing the ``setupCSRFToken()`` call in the ``demo/demo/builder/templates/formidable/formidable_base.html `` file.
If you try to save, it throws a 403. You can inspect if using your favorite browser dev tool, it's about CSRF value not provided.
**Note:** you can't use the master code, it breaks because of the empty URL in the urlpatterns.
=> Fix demo site for logged in users

CHANGELOG.rst, demo/demo/__init__.py, demo/demo/builder/templates/formidable/formidable_list.html, demo/demo/settings.py, demo/requirements-demo.pip, demo/tests/__init__.py, demo/tests/test_post_save_callbacks.py, demo/tests/test_post_save_callbacks_regression_tests.py, demo/tests/tests_integration.py, docs/source/callbacks.rst, docs/source/index.rst, formidable/__init__.py, formidable/app.py, formidable/views.py, tox.ini
=> Added a callback mechanism when creating / updating a form via the builder

formidable/__init__.py, setup.py
Since the version is set in `setup.py`, it's not available in formidable
module itself. I suggest to set the version in `formidable/__init__.py`
instead.
=> [setup] Expose version in formidable package

CHANGELOG.rst, demo/demo/settings.py, demo/django18_sqlite3_backend/__init__.py, demo/django18_sqlite3_backend/base.py, demo/django18_sqlite3_backend/operations.py, demo/requirements-demo.pip, demo/tests/perfs/test_end_point.perf.yml, demo/tests/perfs/tests_integration.perf.yml, demo/tests/test_end_point.py, demo/tests/tests_integration.py, formidable/serializers/fields.py, formidable/serializers/items.py, formidable/urls.py, formidable/views.py
=> add django-perf-rec module and use it to improve SQL queries in many views/processes

CHANGELOG.rst, demo/tests/perfs/test_end_point.perf.yml, demo/tests/perfs/tests_integration.perf.yml, demo/tests/test_end_point.py, demo/tests/tests_integration.py, formidable/serializers/fields.py, formidable/views.py
=> Deduplicate queries retrieve builder view

formidable/accesses.py, formidable/exceptions.py, formidable/forms/fields.py
Spotted while checking something into Formidable code.
=> Rename exception class for unknown access

CHANGELOG.rst, demo/tests/test_models.py, formidable/models.py
=> [models] Add str() methods

CHANGELOG.rst, tox.ini
=> ignore the .crowdin directory for the flake8 tox job.

setup.cfg
Python3's ConfigParser does not support inline comments in config files
The way it was parsed caused isort to crash because of a bad value for
`multi_line_output`
=> fix setup.cfg parsing with python3

CHANGELOG.rst, demo/tests/perfs/test_end_point.perf.yml, demo/tests/perfs/tests_integration.perf.yml, demo/tests/test_end_point.py, demo/tests/test_presets.py, demo/tests/tests_integration.py, formidable/forms/__init__.py, formidable/forms/validations/presets.py, formidable/serializers/forms.py, formidable/serializers/presets.py
=> add presets to ContextFormSerializer

CHANGELOG.rst, circle.yml
I've split CircleCI jobs into:
* `tox -e $(tox -l | grep django18 | tr '\n' ',')`
* `tox -e $(tox -l | grep django19 | tr '\n' ',')`
* `tox -e flake8`
* `tox -e isort-check`
This way, we can spot more quickly which jobs have failed, without reading the full log of the previous job.
=> [ci] Split tox jobs into CircleCI configuration

demo/tests/test_forms.py, formidable/forms/validations/presets.py
As a field is not mandatory
If empty, it should be accepted
=> Skip form validation rules if a field is empty

CHANGELOG.rst, demo/tests/test_end_point.py, formidable/serializers/fields.py, formidable/serializers/items.py, formidable/serializers/presets.py
catch up API changes in formidable-ui
=> Change `help_text` to `description` in the API

formidable/models.py
We use the `@python_2_unicode_compatible` python decorator to give our
models both `__str__` and `__models__`
See https://docs.djangoproject.com/en/1.10/topics/python3/#str-and-unicode-methods
=> Define __unicode__ and __str__ on models

demo/tests/test_end_point.py, demo/tests/tests_integration.py, formidable/serializers/presets.py, formidable/views.py
In order to return a serialized Presets list, we tried to instantiate
presets with `arguments=[]`. But checks are done in `Presets.__init__`
on the arguments provided. This resulted in an `ImproperlyConfigured`
Exception.
The Serializer now takes the class as `instance` parameter instead of an
object.
=> Fix error on presets_lists endpoint

CHANGELOG.rst, demo/tests/tests_integration.py, formidable/serializers/access.py, formidable/serializers/fields.py, formidable/serializers/list.py
Fix unhandled exception in some cases and allows for better error reporting.
=> Check for unicity in NestListSerializers

CHANGELOG.rst, README.rst, circle.yml, setup.py, tox.ini
=> Added Django 1.10 support

CHANGELOG.rst, demo/tests/test_forms.py, formidable/forms/field_builder.py
the data found in clean_data is then `'False'` (str) instead of `False`
(bool)
This PR closes #208
=> Checkbox uses a CharField instead of a BooleanField

CHANGELOG.rst, demo/tests/test_form_from_schema.py, demo/tests/test_from_form.py, formidable/forms/__init__.py, formidable/forms/field_builder.py, formidable/forms/field_builder_from_schema.py, formidable/forms/validations/presets.py, formidable/validators.py
When the contextualized schema is already stored in database (First step to reach the versioning directly in formidable) generate the associated django form class.
```python
schema = ContextFormSerializer(instance=formidable, context={
'role': 'jedi'
}).data
form_class = get_dynamic_form_class_from_schema(schema)
form = form_class(data={'first_name': 'Obiwan', 'last_name': 'Kenobi'})
form.is_valid()
```
=> Provide a tools in order to generate django-form class from json contextualized definition

CHANGELOG.rst, formidable/__init__.py
ChangeLog
---------
* Added Django 1.10 support (#203).
* Dropped Python 3.3 support (#207).
* Fixed the swagger doc generation and rendering (#210).
* Fix wrong field type for Checkbox (#208).
* Don't rely on database ordering in `NestedListSerializer` (#215)
* Provide a tools in order to generate django-form class from json
contextualized definition (#171)
=> Release version 0.9.0

formidable/forms/widgets.py
=> Change format widget input_type

CHANGELOG.rst, demo/tests/test_models.py, formidable/migrations/0003_item_label_no_size_limit.py, formidable/models.py
=> Remove the field size limit for the model field `formidable.models.Item.label`

demo/tests/test_conditions.py, demo/tests/test_end_point.py, formidable/forms/conditions.py, formidable/migrations/0005_conditions_default.py, formidable/serializers/forms.py
Fix 3 issues with conditions introduced in previous commits but not yet released. 
- missing django db migration for default value on `conditions`
- remove fields from the generated django form if they are hidden by the conditional fields
- save() was not done properly on create/update.
Note on the last point : if we create a form with conditions, there will be one extra SQL request to update the form and add the conditions (easier way to handle nested JSONField with DRF)
=> Fix conditions save

CHANGELOG.rst, circle.yml, demo/demo/urls.py, demo/demo/views.py, demo/tests/perfs/test_integration.perf.yml, demo/tests/test_integration.py, demo/tests/test_permissions.py, formidable/forms/__init__.py, formidable/views.py
ValidateView needs a Formidable object.
We had issues in test because, when we need to delete a setting, tests
require to be decorated with `@override_settings()` without any
argument.
> You can also simulate the absence of a setting by deleting it after
> settings have been overridden, like this:
> ```python
> @override_settings()
> def test_something(self):
>     del settings.LOGIN_URL
>     ...
> ```
> — django.test.modify_settings [1]
For CircleCI, we needed to upgrade `virtualenv` package as well as `tox`
because tests were failing with an old version of the package.
References:
[1] https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.modify_settings
=> Add a ValidateView that works with ContextForm JSON

CHANGELOG.rst, Makefile, README.rst
this will fire up a small Python HTTP server to browse the documentation 
locally.
=> Added a new "serve-docs" target to the makefile

CHANGELOG.rst, Makefile, docs/source/_static/specs/formidable.js, docs/source/deprecations.rst, docs/source/index.rst, docs/swagger/formidable.yml, formidable/__init__.py
- Warnings in the Sphinx documentation (deprecations timeline page)
- Added a Deprecation warning about Presets in the swagger specs.
- ``DeprecationWarning`` warnings at runtime,
- Changelog updated
- (unrelated: added a Makefile target to build swagger statics independently)
This PR will close #239 and will close #249
=> Deprecation warnings for Presets and DRF 3.3

CHANGELOG.rst, formidable/migrations/0006_drop_preset_fields.py
Don't drop tables, drop only fields.
The tables will be dropped in a further Django migration, and the appropriate release (post 1.0.0)
refs #255
=> Drop preset fields

CHANGELOG.rst, demo/tests/test_integration.py, formidable/views.py
=> Validate review returns the right content type

CHANGELOG.rst, README.rst, tox.ini
=> Reflect incompatibility between Django 1.8 and DRF 3.7 by changing requirements in tox tests

CHANGELOG.rst, README.rst, setup.py
=> Migrate to PeopleDoc's organization

CHANGELOG.rst, docs/source/dev.rst, formidable/__init__.py
Before:
```sh
$ cd project/root/directory
$ pytest
[..]
ImportError: No module named demo.settings
pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
```
What we need is to go to the `demo` directory in order to have the Django Settings Module correctly picked up.
=> [Doc] Fixed a missing ``cd`` in docs. You can't run pytest from project root.

CHANGELOG.rst, demo/tests/test_integration.py, docs/package-lock.json, docs/source/_static/specs/formidable.js, docs/swagger/formidable.yml, formidable/views.py
=> Allow post method validation endpoint

CHANGELOG.rst, demo/tests/test_integration.py, demo/tests/test_perfs_rec.py, docs/source/_static/specs/formidable.js, docs/source/deprecations.rst, docs/swagger/formidable.yml, formidable/views.py
=> Disallow GET method for user-data validation URL

CHANGELOG.rst, demo/tests/test_conditions.py, demo/tests/test_end_point.py, docs/source/forms.rst, formidable/forms/__init__.py, formidable/forms/conditions.py, formidable/serializers/forms.py
This PR uses the same test suite as defined in https://github.com/peopledoc/django-formidable/pull/299
A few notes:
At the moment, ``Conditions`` are only used for defining conditional display of fields. But if we inspect its implementation, we'll find that it's being built around a bigger scope, that is to say that they're built to be as "generic" as possible. Virtually, ``Condtions`` could lead to a variety of actions.
In the meantime, the ``display_iff`` action defined in the present code had a definitive impact on the form: having only *one* "hide this field" action would **wipe it out** from the form fields and ``cleaned_data`` and ``errors``... My opinion on this, regardless of the evolution we're trying to implement here, is that the ``Condition`` object was way too powerful.
The …
=> Add support for multiple conditions to target a common field

CHANGELOG.rst, formidable/__init__.py
**Deprecation Warning**: The validation endpoint (using the URL ``forms/(?P<pk>\d+)/validate/``) is now ``POST`` only.
- Added tests against the ``formidable.yml`` schema definition of Forms (#295).
- Fixed various items in the schema definition (#297).
- Validation endpoint for **user data** doesn't allow GET method anymore (#300).
- Add support for multiple conditions to target a common field.
=> Release 1.4.0

CHANGELOG.rst, demo/tests/fixtures/conditions-contextualization.json, demo/tests/test_conditions.py, formidable/serializers/forms.py
* We're going to pass this hotfix on master, in order to be able to test the changeset using the latest UI lib.
* All the "code" commits will be squashed into one, and we'll leave the "changelog" commit by itself
* The "code" commit will be cherry-picked and applied to the existing tags (1.2.1, 1.3.0, 1.4.0) to backport the changeset to previous stable releases.
=> Conditional rules contextualization

CHANGELOG.rst
In order to have all the Changelog entries in our changelog, and make sure that all the tags are contained in the master branch.
=> Mergeing backport releases into master

.gitignore, CHANGELOG.rst, demo/requirements-demo.pip
This PR fix tests error with the typing for python2. Read more here https://github.com/django-extensions/django-extensions/issues/1176
=> Added typing to the demo requirements, added pytest cache to the gitignore

CHANGELOG.rst, demo/tests/fixtures/drop-down-conditions.json, demo/tests/fixtures/test_conditions.py, demo/tests/test_conditions.py, demo/tests/test_integration.py, docs/source/_static/specs/formidable.js, docs/source/forms.rst, formidable/forms/conditions.py, formidable/serializers/forms.py
Conditional rules are tested and documented for usage with checkboxes. We want to make sure it is possible to use conditional rules based on dropdown lists, by testing and documenting it.
=> Add tests for conditional rules based on dropdown

CHANGELOG.rst, demo/tests/test_integration.py, formidable/views.py
This content is the spec-compatible content to pass along with a 204 HTTP status response.
Before this hotfix, the dictionary passed along as the response content was serialized into a 2-character string to calculate the content-length, but this content was not returned to the client. Some browsers would experience it badly, namely IE11.
=> Make sure that the `ValidateView.form_valid` method return an actual empty body content

CHANGELOG.rst, formidable/app.py
=> Add a deprecation warning for django 1.8 and 1.9

CHANGELOG.rst, demo/tests/test_form_from_schema.py, formidable/models.py, formidable/serializers/forms.py
This would ensure that stored schemas would carry their version and wouldn't need extra JSON schema migrations.
=> Added the JSON ``version`` when going through the ``Formidable.to_json()`` class method

CHANGELOG.rst, formidable/models.py, formidable/serializers/forms.py
The serializer is called by the method, so it's idempotent.
=> Moved the injection of the JSON ``version`` into the serializer, rather than the ``Formidable.to_json()`` class method.

.circleci/config.yml, CHANGELOG.rst
PeopleDoc has a limited number of workers, using this Docker Image allows us to spare resources.
=> Optimize the CircleCI build by using less workers

.circleci/config.yml, CHANGELOG.rst
And still, this `--user` install isn't used because the tox package installed by the docker image is the first in the `$PATH`.
=> CircleCI optimization: do not install tox, it's already there

CHANGELOG.rst, demo/tests/test_conditions.py, demo/tests/test_forms.py, formidable/forms/field_builder.py, formidable/forms/field_builder_from_schema.py
This PR is targeting release/2.1 in order to make a new hotfix release
=> Hotfix disable widgets

CHANGELOG.rst, demo/demo/extra_field_toolbox.py, demo/tests/fixtures/form-schema-extra-fields.json, demo/tests/serializers/test_formidable_serializer.py, demo/tests/test_extra_field_filler.py, docs/source/external-field-plugins.rst, formidable/forms/__init__.py, formidable/forms/field_builder.py, formidable/serializers/child_proxy.py, formidable/serializers/fields.py, formidable/utils.py
=> Form filler extra fields

CHANGELOG.rst, demo/requirements-demo.pip, demo/tests/serializers/test_formidable_serializer.py, formidable/serializers/fields.py
=> fields parameters are not the write-only anymore

CHANGELOG.rst, demo/demo/extra_field_toolbox.py, demo/tests/test_field_parameters.py, docs/source/external-field-plugins.rst, formidable/forms/fields.py, formidable/forms/widgets.py
=> Enable Widgets be used by to_formidable() for extra-fields

.circleci/config.yml, CHANGELOG.rst
Circle-CI images fails to build.
ref: https://circleci.com/gh/peopledoc/django-formidable/1607
We need a node image able to install Python, or the other way around.
=> Documentation build is KO

CHANGELOG.rst, README.rst, demo/tests/fixtures/form-data.json, demo/tests/perfs/test_perfs_rec.perf.yml, demo/tests/test_integration.py, demo/tests/test_perfs_rec.py, setup.py
Originating this PR: a moderate security alert on Django REST Framework. Although we don't use the incriminated feature, we _had_ to upgrade our supported version.
The patch wasn't supposed to impact tests, because there's no apparent regression on our runtime codebase. Although, it raised an issue in our "Perf Rec" tests, that were trying to create forms with the wrong TestClient.
The consequence of this mishandling of the "POST" method was that the Formidable object was created, but none of its "children" (fields, accesses, validations, conditions, etc).
Switching to the DRF APITestClient and passing the `format='json'` argument led to fix the form creation. As a consequence, the SQL queries executed now reflect the creation of the objects in the Database *and* their retrieval …
=> Upgrading dependency to Django REST Framework up to 3.9.x

CHANGELOG.rst, tox.ini
My goal here is to prove that Django-Formidable works with any version of DRF between 3.8 and 3.9, up to the current 3.9.x
=> Extend the test matrix to spread through different DRF versions

CHANGELOG.rst, README.rst, docs/source/deprecations.rst, tox.ini
EOL was in December 2nd, 2017.
* Added deprecation mention in the docs,
* Changed a few obsolete items in the readme.
=> Drop support for Django 1.10

.circleci/config.yml, CHANGELOG.rst, demo/demo/settings_test_pg.py, demo/tests/perfs/test_integration.perf.yml, demo/tests/perfs/test_perfs_rec.perf.yml, demo/tests/test_end_point.py, demo/tests/test_integration.py, demo/tests/test_perfs_rec.py, docs/source/dev.rst, tox.ini
* Perf-recs are differentiated,
* Dev docs updated to explain how to run tests locally,
closes #161
=> Run tests in PG, both locally and on Circle-CI

CHANGELOG.rst, demo/tests/perfs/test_perfs_rec.perf.yml, demo/tests/test_integration.py, demo/tests/test_perfs_rec.py, formidable/exception_handler.py, formidable/serializers/forms.py, formidable/views.py
The main use-case is ``PUT`` and ``PATCH`` views.
This could prevent Database deadlocks when several changes are attempted on the same **large** form.
The only place where ``select_for_update()`` is used is on the save() of the Form. It should prevent further calls to the API to request the change because, as far as I can say, here is what happens:
1. the transaction is started,
2. the "for update" lock is requested on the form record,
3. the other operations (update/delete/create of "children") happen,
4. the transaction is committed and thus, the lock is released.
As soon as step 2 is launched, any other session that would want to lock the record fail and a `DatabaseError` would be raised. And as we don't have any endpoint in the API that allow modifications of children records, this …
=> Add ``select_for_update()`` on selection when the Form is modified

CHANGELOG.rst, README.rst, demo/demo/builder/views.py, demo/demo/settings.py, demo/demo/urls.py, demo/tests/test_exception_handler.py, demo/tests/test_fields.py, demo/tests/test_integration.py, demo/tests/test_perfs_rec.py, demo/tests/test_post_save_callbacks.py, demo/tests/test_post_save_callbacks_regression_tests.py, docs/source/deprecations.rst, formidable/forms/widgets.py, formidable/migrations/0001_initial.py, formidable/models.py, tox.ini
Django Formidable should probably work on Django 2.0 and 2.1, but it's not in our test suite. We've decided to skip those versions because of their short-term support.
closes #326
=> Added support for Django 2.2

CHANGELOG.rst, docs/source/deprecations.rst, formidable/__init__.py
- Add support to Django 2.2 (#326).
- Add support to Python 3.7 & 3.8 (#374).
=> Release 3.3.0

CHANGELOG.rst, tox.ini
=> Removed tox.ini directive that skipped missing Python interpreters

CHANGELOG.rst, README.rst, docs/source/deprecations.rst, formidable/__init__.py
* Dropping Python 2 support
* XSS Prevention mechanism added
=> Release 4.0.0

.circleci/config.yml, CHANGELOG.rst, README.rst, demo/tests/test_app.py, docs/source/deprecations.rst, formidable/app.py, tox.ini
* A warning is raised,
* Deprecation documentation is amended,
* Readme is amended to warn the user about this potential runtime failure.
This PR closes #395
=> Warn integrators about incompatibilities with jsonfield & Django 1.11

CHANGELOG.rst, README.rst, demo/demo/urls.py, demo/tests/test_app.py, demo/tests/test_end_point.py, docs/source/deprecations.rst, formidable/app.py, formidable/forms/conditions.py, tox.ini
=> Drop django1.11 support

CHANGELOG.rst, demo/tests/test_defaults_with_accesses.py, formidable/forms/field_builder.py
Issue: default values for readonly fields are cleaned, we want to keep them.
=> Improve default values for readonly fields

CHANGELOG.rst, demo/tests/test_integration.py, formidable/forms/field_builder.py
Something was missing in the last PR, the validation from schema was still broken in case of empty defaults.
This PR closes #
=> Fix defaults on readonly during validation from schema

.circleci/config.yml, CHANGELOG.rst, README.rst, docs/source/deprecations.rst, setup.py, tox.ini
=> Dropped support for Python 3.5

CHANGELOG.rst, demo/tests/test_forms.py, formidable/models.py
We had issues with missing context in to_internal_value, when called
from `from_json` method.
This PR allows to pass a context to `from_json`. It will be given to the
serializer to be used in validations.
This PR closes #
=> Pass context to serializer in from_json

CHANGELOG.rst, setup.py
It said BSD, while it was MIT since the beginning. Thx @jayvdb for the heads-up!
This PR closes #402
=> Fix license reference in setup.py

CHANGELOG.rst, docs/source/deprecations.rst, formidable/__init__.py
Even though this change is not *breaking* (because forms generated prior to 7.0.0 would still work), this version is marked as a major release. Because it changes the database schema, and implies a database migration.
=> Release 7.0.0

CHANGELOG.rst, README.rst, docs/source/deprecations.rst, tox.ini
=> Add/Confirm support of Django REST Framework 3.11

CHANGELOG.rst, tox.ini
=> Pin psycopg-binary to 2.8 to fix CI

CHANGELOG.rst, demo/tests/serializers/test_validations.py, formidable/serializers/validation.py
=> Future date validation accept bool values
