- circle.yml
- demo/tests/test_end_point.py
- formidable/accesses.py
- formidable/forms/validations/presets.py
- formidable/serializers/child_proxy.py
- formidable/serializers/common.py
- formidable/serializers/validation.py
- tox.ini
> Make python34 compatibility

- demo/tests/test_end_point.py
- demo/tests/test_forms.py
- doc/source/forms.rst
- formidable/constants.py
- formidable/forms/fields.py
- formidable/models.py
- formidable/serializers/access.py
- formidable/serializers/fields.py
> refs #88, define access as constants

- demo/tests/tests_integration.py
- formidable/accesses.py
- formidable/urls.py
- formidable/views.py
> Validate data through api

- CHANGELOG.rst
- setup.py
Release 0.1.0 (2016-06-29)
==========================
* Define constants for access right 2 - Working <= 5 enhancement (#88)
* Disabled field don't send data on submit! bug question (#79)
* Turn defaults value into a list of strings refactor (#77)
* Rename value to label for fields items refactor (#76)
* Ordre des items dans les fields à choix. (#69)
* Define ``FileField`` in FieldBuilder (pure Django) (#68)
* Fix radiobutton type ID through JS builder (#67)
* Python 3/2 compatibility (#66)
* Fix multiple choices in the final Django Form class (#63)
* Fix the order field creation and rendering in data serialization (#61)
* Add validation Presets (#60)
* Rename "helpText" to "help_text" (#57)
* Add docs (#53)
* Implement TitleField/SeperateField/HelpTextField (#51)
* Add contextualized …
> Release 0.1.0

- circle.yml
- demo/demo/builder/urls.py
- demo/requirements-demo.pip
- formidable/urls.py
- setup.py
- tox.ini
* Add support for Django 1.9
* Remove pattern() in urls.py
* Add Django/Python matrix to tox configuration
> Add support for Django 1.9

- CHANGELOG.rst
- Makefile
Following a simple convention, the Makefile is self-documented
> Added Makefile autodocumentation

- CHANGELOG.rst
- demo/demo/builder/admin.py
- demo/demo/builder/models.py
- demo/demo/builder/tests.py
- demo/tests/test_end_point.py
- demo/tests/test_forms.py
- demo/tests/tests_integration.py
- docs/source/conf.py
- formidable/forms/validations/presets.py
- formidable/migrations/0001_initial.py
- formidable/serializers/list.py
- tox.ini
Because my editor said it had some flake8 errors
```
ERROR: InvocationError: '/home/ubuntu/django-formidable/.tox/flake8/bin/flake8 .'
___________________________________ summary ____________________________________
django18-py27: commands succeeded
django18-py33: commands succeeded
django18-py34: commands succeeded
django18-py35: commands succeeded
django19-py27: commands succeeded
django19-py34: commands succeeded
django19-py35: commands succeeded
ERROR:   flake8: commands failed
```
```
django18-py27: commands succeeded
django18-py33: commands succeeded
django18-py34: commands succeeded
django18-py35: commands succeeded
django19-py27: commands succeeded
django19-py34: commands succeeded
django19-py35: commands succeeded
flake8: commands succeeded
congratulations :)
```
```
> Added flake8 checks job in tox

- CHANGELOG.rst
- demo/tests/tests_integration.py
- formidable/forms/validations/presets.py
Add some tests to check error status and message when validating a form that have presets
> check presets messages on validation

- demo/tests/test_end_point.py
- demo/tests/test_forms.py
- demo/tests/test_presets.py
- formidable/forms/__init__.py
- formidable/forms/validations/presets.py
Added tests for Confirmation presets:
* using a left/right field,
* using a field and an arbitrary value
> Confirmation preset tests

- CHANGELOG.rst
- formidable/__init__.py
> Release 0.8.0

- CHANGELOG.rst
- demo/tests/test_end_point.py
- formidable/serializers/fields.py
- formidable/serializers/items.py
> Fix serializer blank description

- CHANGELOG.rst
- formidable/__init__.py
> Release 0.8.1

- circle.yml
- docs/.gitignore
- docs/Makefile
- docs/package.json
- docs/source/api.rst
- docs/source/index.rst
- docs/swagger/formidable.yml
- tox.ini
need swagger-UI to render the file
How to use: http://editor.swagger.io/#!/
> Start API documentation using Swagger

- CHANGELOG.rst
- README.rst
- tox.ini
> Dropped Python 3.3 support

- CHANGELOG.rst
- docs/Makefile
- tox.ini
> Fixed swagger doc generation

- CHANGELOG.rst
- demo/tests/tests_integration.py
- formidable/serializers/list.py
> unique constraint violation in Update

- CHANGELOG.rst
- demo/tests/test_end_point.py
- formidable/serializers/forms.py
> Atomic transactions

- CHANGELOG.rst
- formidable/serializers/list.py
- tox.ini
> Compatibility drf lt 3.5

- CHANGELOG.rst
- demo/tests/test_post_save_callbacks.py
- demo/tests/test_post_save_callbacks_regression_tests.py
- demo/tests/tests_integration.py
- formidable/exception_handler.py
- formidable/serializers/forms.py
- formidable/views.py
> Change errors format in the builder

- CHANGELOG.rst
- demo/tests/test_end_point.py
- demo/tests/test_form_from_schema.py
- demo/tests/test_forms.py
- demo/tests/test_from_form.py
- demo/tests/tests_integration.py
- formidable/forms/field_builder.py
- formidable/forms/field_builder_from_schema.py
- formidable/forms/fields.py
- formidable/validators.py
> Float numberfield

- CHANGELOG.rst
- demo/tests/tests_integration.py
- formidable/urls.py
> Make trailing slash not mandatory for the API

- CHANGELOG.rst
- formidable/__init__.py
- formidable/locale/de/LC_MESSAGES/django.po
- formidable/locale/en_GB/LC_MESSAGES/django.po
- formidable/locale/en_US/LC_MESSAGES/django.po
- formidable/locale/es/LC_MESSAGES/django.po
- formidable/locale/fr/LC_MESSAGES/django.po
- formidable/locale/it/LC_MESSAGES/django.po
- formidable/locale/nb/LC_MESSAGES/django.po
- formidable/locale/nl/LC_MESSAGES/django.po
- formidable/locale/pl_PL/LC_MESSAGES/django.po
- formidable/locale/pt_BR/LC_MESSAGES/django.po
- formidable/locale/tr_TR/LC_MESSAGES/django.po
- formidable/locale/zh_CN/LC_MESSAGES/django.po
> Release 0.11.1

- CHANGELOG.rst
- README.rst
- circle.yml
- demo/demo/settings.py
- demo/requirements-demo.pip
- demo/tests/json_migrations/0001_rename_helptext.py
- demo/tests/json_migrations/0002_add_version.py
- demo/tests/test_json_migrations.py
- docs/source/intro.rst
- formidable/json_migrations/0001_rename_helptext_to_description.py
- formidable/json_migrations/__init__.py
- setup.py
- tox.ini
> JSON Schema Migration

- CHANGELOG.rst
- demo/tests/test_end_point.py
- formidable/json_migrations/utils.py
- formidable/models.py
add a tool to merge contextformsJSON into FormidableJSON
> Merge context forms

- CHANGELOG.rst
- demo/tests/test_conditions.py
- demo/tests/test_end_point.py
- formidable/forms/validations/presets.py
- formidable/serializers/fields.py
- formidable/serializers/list.py
- tox.ini
One day... one day, I'll understand how and why it's possible...
> Fixing a few flake8 errors that weren't detected in the CI

- CHANGELOG.rst
- demo/tests/test_end_point.py
- demo/tests/test_form_from_schema.py
- formidable/forms/field_builder_from_schema.py
- formidable/models.py
- formidable/serializers/forms.py
> Add contextualize function for form definition

- CHANGELOG.rst
- formidable/__init__.py
> [Release] 0.13.0

- CHANGELOG.rst
- demo/tests/test_form_from_schema.py
- formidable/forms/field_builder_from_schema.py
Separator does not have label or description/help_text
Title does not have description/help_text
> Fix field builder from schema

- CHANGELOG.rst
- formidable/__init__.py
> Release 0.13.1

- CHANGELOG.rst
- formidable/__init__.py
- tox.ini
> Drop Django REST Framework 3.3.x version support

- CHANGELOG.rst
- demo/tests/test_exception_handler.py
- demo/tests/test_integration.py
- formidable/exception_handler.py
- formidable/forms/conditions.py
> Fix a 500 error with Mandatory File Fields and conditional display

- CHANGELOG.rst
- formidable/__init__.py
> Release v1.0.1

- README.rst
> Fixed the link to the Deprecation Timeline doc on the README

- CHANGELOG.rst
- demo/tests/test_validators.py
- formidable/forms/__init__.py
- formidable/forms/conditions.py
- formidable/forms/field_builder.py
- formidable/register.py
- formidable/serializers/fields.py
- formidable/serializers/list.py
- formidable/serializers/validation.py
- formidable/validators.py
- formidable/views.py
> Fix pep8 and minor changes

- demo/tests/test_validators.py
> #279 Fix tests on the mutable objects.

- CHANGELOG.rst
- demo/tests/fixtures/form-data-changed.json
- demo/tests/fixtures/form-data.json
- demo/tests/perfs/test_perfs_rec.perf.yml
- demo/tests/test_perfs_rec.py
This PR closes #153 
Please check the records structure.
> #153 Added perf-rec tests for the views

- CHANGELOG.rst
- demo/tests/test_models.py
- formidable/migrations/0008_formidable_item_value_field_size.py
- formidable/models.py
> Enlarge formidable item value size

- demo/tests/fixtures/migration-form-data-expected.json
- demo/tests/fixtures/migration-form-data-input.json
- demo/tests/test_json_migration_utils.py
- formidable/forms/field_builder_from_schema.py
- formidable/json_migrations/utils.py
> FORM-13: Fix JSON migrations

- CHANGELOG.rst
- demo/tests/fixtures/wrong-conditions.json
- demo/tests/test_conditions.py
- formidable/forms/conditions.py
- tox.ini
current user type
This PR closes #
> Do not raise an exception when conditional field is not visible 

- CHANGELOG.rst
- demo/tests/fixtures/wrong-conditions.json
- demo/tests/test_conditions.py
- formidable/serializers/forms.py
This PR closes #4916
PR to show only existing fields ids in the conditions.
> Filter conditional rules

- CHANGELOG.rst
- demo/tests/test_conditions.py
- demo/tests/test_end_point.py
- formidable/forms/conditions.py
- formidable/serializers/forms.py
> Allow null or empty condition name

- CHANGELOG.rst
- README.rst
- circle.yml
- tox.ini
> Added compatibility tests with Django 1.11

- CHANGELOG.rst
- README.rst
- circle.yml
- setup.py
- tox.ini
> Added Python 3.6 support

- demo/tests/test_post_save_callbacks_regression_tests.py
to make sure we have the correct field type.
> Added further tests when updating a form and changing a field type while keeping the same slug

- CHANGELOG.rst
- demo/tests/test_post_save_callbacks_regression_tests.py
- formidable/serializers/child_proxy.py
This PR closes FORM-407
I'm not sure that this is the best solution, but I tried a few different and it looks better for me. So please, if you have any idea about improvements, I will be happy to do it.
> Change field type support

- CHANGELOG.rst
- docs/Makefile
- docs/source/_static/specs/formidable.json
- docs/source/conf.py
- docs/source/form-specs.rst
- docs/source/index.rst
- tox.ini
> Added a tool to build the Formidable JSON Schema and include it into the docs

- docs/requirements.pip
- docs/source/deprecations.rst
- tox.ini
see: https://readthedocs.org/projects/django-formidable/builds/7073200/
> Fix doc build

- CHANGELOG.rst
- demo/tests/test_exception_handler.py
- formidable/exception_handler.py
> Better information when a server error occurs.

- demo/tests/test_forms.py
- formidable/forms/field_builder.py
This PR targets `make_widget_customisation_working`
> Fix tests & various indent fixes

- CHANGELOG.rst
- README.rst
- demo/tests/serializers/test_validations.py
- formidable/views.py
- setup.py
> Django REST Framework incompatibilities & co.

- CHANGELOG.rst
- demo/requirements-demo.pip
- demo/tests/test_end_point.py
- formidable/serializers/fields.py
- formidable/serializers/items.py
- tox.ini
> Clean up help_text migration (#292)

- CHANGELOG.rst
- docs/source/deprecations.rst
- formidable/__init__.py
> Release v3.2.0

- CHANGELOG.rst
- README.rst
- setup.py
- tox.ini
```sh
$ tox -l | wc -l
49
```
I'd be glad to remove some combinations when it'll be possible, to be honest.
> Added Python 3.7 & 3.8 compatibility

- CHANGELOG.rst
- demo/demo/security.py
- demo/demo/settings.py
- demo/requirements-demo.pip
- demo/tests/__init__.py
- demo/tests/test_integration_xss.py
- docs/source/index.rst
- docs/source/security.rst
- formidable/security.py
- formidable/serializers/defaults.py
- formidable/serializers/fields.py
- formidable/serializers/forms.py
> Prevent XSS attacks by enabling a cleanup method

- CHANGELOG.rst
- setup.py
> DOC: removed ``setup.py`` Python2-related classifiers.

- CHANGELOG.rst
- demo/tests/fixtures/multiple-choices-conditions.json
- demo/tests/fixtures/test_conditions.py
- demo/tests/test_conditions.py
- demo/tests/test_integration.py
- formidable/forms/conditions.py
> Fix conditional rules multiple answers

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- README.rst
- demo/requirements-demo.pip
- docs/source/deprecations.rst
- tox.ini
> Drop support for Django REST Framework 3.8

- CHANGELOG.rst
- demo/tests/serializers/test_formidable_serializer.py
- formidable/migrations/0010_auto_20200213_1010.py
- formidable/models.py
> Allow empty defaults value hotfix

- CHANGELOG.rst
- demo/tests/serializers/test_formidable_serializer.py
- formidable/__init__.py
- formidable/migrations/0010_auto_20200213_1010.py
- formidable/models.py
> Transfer 4.0.2 into master

- CHANGELOG.rst
- Makefile
- docs/source/dev.rst
- formidable/accesses.py
- formidable/exception_handler.py
- formidable/forms/conditions.py
- formidable/forms/field_builder.py
- formidable/forms/fields.py
- formidable/migrations/0010_auto_20200213_1010.py
- formidable/models.py
- formidable/serializers/child_proxy.py
- formidable/serializers/fields.py
- formidable/serializers/validation.py
- formidable/validators.py
- formidable/views.py
> Python2 cleanups

- CHANGELOG.rst
- demo/tests/serializers/test_formidable_serializer.py
- formidable/serializers/fields.py
> Include parameters when serializing a form using the ContextFormSerializer

- CHANGELOG.rst
- formidable/models.py
- formidable/serializers/access.py
- formidable/serializers/defaults.py
- formidable/serializers/fields.py
- formidable/serializers/forms.py
- formidable/serializers/items.py
- formidable/serializers/validation.py
- formidable/views.py
- setup.cfg
- tox.ini
> Applied isort v5+ changes

- CHANGELOG.rst
- demo/tests/__init__.py
- demo/tests/test_integration.py
- formidable/forms/field_builder.py
> Fix default values for date field

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- docs/source/index.rst
- docs/source/maintainers.rst
> Added a thorough documentation for maintainers

- .circleci/config.yml
- CHANGELOG.rst
- demo/tests/serializers/test_formidable_serializer.py
- docs/Makefile
- docs/package-lock.json
- docs/source/_static/swagger-ui/package.json
- docs/tests/__init__.py
- formidable/serializers/forms.py
- Some parts of the code are iterating through conditions but it was possible to have None conditions.
- Also CI fixes: doc build and postgres.
> Fix conditions default value

- CHANGELOG.rst
- demo/demo/builder/urls.py
- demo/demo/urls.py
- demo/tests/perfs/test_integration.perf.yml
- demo/tests/perfs/test_perfs_rec.perf.yml
- demo/tests/test_integration.py
- demo/tests/test_perfs_rec.py
- formidable/forms/boundfield.py
- formidable/urls.py
- tox.ini
- Add Django 3 support
- Drop DRF<3.11 because previous DRF versions do not support Django 2 (ImportErrors within DRF)
> Django3 compatibility
